require "import"
import "android.widget.*"
import "android.view.*"
import "android.app.*"
import "android.graphics.*"
import "android.view.animation.*"
import "android.speech.tts.TextToSpeech"
import "java.util.Locale"
import "android.os.Handler"
import "android.os.Looper"
import "android.content.ClipboardManager"
import "android.content.ClipData"
import "android.content.Context"
import "android.content.SharedPreferences"
import "android.content.Intent"
import "android.net.Uri"
import "android.content.DialogInterface"
import "android.view.inputmethod.InputMethodManager"
import "java.io.File"
import "com.androlua.Http"
import "cjson"
import "com.androlua.LuaDialog"

-- Safe Context Initialization